### ISSUE TITLE
Response Bad Request For CONNECT

### ISSUE THREAD

**Issue by emag** [emag/morecat_old#75]
まあ、なんらかの対応を

```
2014-08-22 00:20:33,047 ERROR [io.undertow.request] (default I/O-4) Blocking request failed HttpServerExchange{ CONNECT mx2.mail2000.com.tw:25}: java.lang.IllegalArgumentException: UT000068: Servlet path match failed
        at io.undertow.servlet.handlers.ServletPathMatchesData.getServletHandlerByPath(ServletPathMatchesData.java:85)
        at io.undertow.servlet.handlers.ServletPathMatches.getServletHandlerByPath(ServletPathMatches.java:75)
        at io.undertow.servlet.handlers.ServletInitialHandler.handleRequest(ServletInitialHandler.java:108)
        at io.undertow.server.handlers.HttpContinueReadHandler.handleRequest(HttpContinueReadHandler.java:43)
        at io.undertow.server.handlers.PathHandler.handleRequest(PathHandler.java:56)
        at io.undertow.server.handlers.accesslog.AccessLogHandler.handleRequest(AccessLogHandler.java:94)
        at io.undertow.server.handlers.HttpContinueReadHandler.handleRequest(HttpContinueReadHandler.java:43)
        at io.undertow.server.handlers.SetHeaderHandler.handleRequest(SetHeaderHandler.java:49)
        at io.undertow.server.handlers.SetHeaderHandler.handleRequest(SetHeaderHandler.java:49)
        at io.undertow.server.handlers.NameVirtualHostHandler.handleRequest(NameVirtualHostHandler.java:57)
        at io.undertow.server.handlers.error.SimpleErrorPageHandler.handleRequest(SimpleErrorPageHandler.java:76)
        at io.undertow.server.handlers.CanonicalPathHandler.handleRequest(CanonicalPathHandler.java:43)
        at io.undertow.server.handlers.ChannelUpgradeHandler.handleRequest(ChannelUpgradeHandler.java:158)
        at io.undertow.server.Connectors.executeRootHandler(Connectors.java:177)
        at io.undertow.server.protocol.http.HttpReadListener.handleEventWithNoRunningRequest(HttpReadListener.java:156)
        at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:91)
        at io.undertow.server.protocol.http.HttpOpenListener.handleEvent(HttpOpenListener.java:92)
        at io.undertow.server.protocol.http.HttpOpenListener.handleEvent(HttpOpenListener.java:43)
        at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92) [xnio-api-3.2.2.Final.jar:3.2.2.Final]
        at org.xnio.ChannelListeners$10.handleEvent(ChannelListeners.java:291) [xnio-api-3.2.2.Final.jar:3.2.2.Final]
        at org.xnio.ChannelListeners$10.handleEvent(ChannelListeners.java:286) [xnio-api-3.2.2.Final.jar:3.2.2.Final]
        at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92) [xnio-api-3.2.2.Final.jar:3.2.2.Final]
        at org.xnio.nio.NioTcpServerHandle.handleReady(NioTcpServerHandle.java:53) [xnio-nio-3.2.2.Final.jar:3.2.2.Final]
        at org.xnio.nio.WorkerThread.run(WorkerThread.java:539) [xnio-nio-3.2.2.Final.jar:3.2.2.Final]

```

**Comment by emag** [comment]
Move to https://github.com/morec-at/morecat/issues/45
